[package]
name = "orb_wasmtime"
version = "0.1.14"
authors = []
edition = "2021"

[lib]
name = "orb_wasmtime"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.0"
anyhow = "1.0"
crossbeam-channel = "0.5"
wasmtime = "19.0.0"
wabt = "0.10.0"
