[build.env]
passthrough = [
  "RUSTLER_NIF_VERSION"
]

[target.riscv64gc-unknown-linux-gnu]
pre-build = ["apt update && apt install -y cmake"]

[target.aarch64-unknown-linux-gnu]
pre-build = ["apt update && apt install build-essential && apt install libstdc++6 && apt install libclang-dev"]