[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-undefined",
    "-C", "link-arg=dynamic_lookup"
]

[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=-crt-static",
  "-C", "link-arg=-lstdc++",
  "-L", "/usr/lib/gcc/x86_64-linux-gnu/10"
]

[target.aarch64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=-crt-static",
  "-l", "static=stdc++",
  "-L", "/usr/lib/gcc/aarch64-linux-gnu/10"
]
